---

- name: suse | Zypper install
  vars:
    ansible_python_interpreter: "python3"
  community.general.packaging.os.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _zypper }}"
  register: result
  until: result is succeeded
