---
- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: check /etc/localtime
      ansible.builtin.file:
        src: "/usr/share/zoneinfo/Etc/UTC"
        dest: "/etc/localtime"
        mode: "0644"
        state: "link"

    - name: date
      ansible.builtin.command: date
      register: result
      changed_when: result is not succeeded
      failed_when: "'UTC' not in result.stdout"
